// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type CancelRequestRequest struct {
	// Request ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *CancelRequestRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CancelRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Request cancelled
	RequestResponse *components.RequestResponse
}

func (c CancelRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelRequestResponse) GetRequestResponse() *components.RequestResponse {
	if c == nil {
		return nil
	}
	return c.RequestResponse
}
