// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
	"time"
)

type CreateWebhookRequest struct {
	// URL to receive webhook POST requests
	URL string `json:"url"`
	// Event types to subscribe to
	Events []components.WebhookEvent `json:"events"`
}

func (c *CreateWebhookRequest) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *CreateWebhookRequest) GetEvents() []components.WebhookEvent {
	if c == nil {
		return []components.WebhookEvent{}
	}
	return c.Events
}

type Webhook struct {
	ID        string                    `json:"id"`
	URL       string                    `json:"url"`
	Events    []components.WebhookEvent `json:"events"`
	Active    bool                      `json:"active"`
	CreatedAt time.Time                 `json:"created_at"`
	UpdatedAt time.Time                 `json:"updated_at"`
	// HMAC secret for verifying webhook deliveries. Only returned once, when the webhook is created. Store it securely.
	//
	Secret *string `json:"secret,omitzero"`
}

func (w Webhook) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *Webhook) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *Webhook) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *Webhook) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *Webhook) GetEvents() []components.WebhookEvent {
	if w == nil {
		return []components.WebhookEvent{}
	}
	return w.Events
}

func (w *Webhook) GetActive() bool {
	if w == nil {
		return false
	}
	return w.Active
}

func (w *Webhook) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *Webhook) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *Webhook) GetSecret() *string {
	if w == nil {
		return nil
	}
	return w.Secret
}

// CreateWebhookResponseBody - Webhook created
type CreateWebhookResponseBody struct {
	Webhook *Webhook `json:"webhook,omitzero"`
}

func (c CreateWebhookResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWebhookResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateWebhookResponseBody) GetWebhook() *Webhook {
	if c == nil {
		return nil
	}
	return c.Webhook
}

type CreateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook created
	Object *CreateWebhookResponseBody
}

func (c CreateWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateWebhookResponse) GetObject() *CreateWebhookResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
