// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type File struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}

// CreateTemplateRequest - Upload a PDF template with named form fields. Provide exactly one of `file` or `file_url`.
type CreateTemplateRequest struct {
	// Display name for the template
	Name string `multipartForm:"name=name"`
	// PDF file with AcroForm fields (mutually exclusive with `file_url`)
	File *File `multipartForm:"file,name=file"`
	// URL to fetch the PDF from (mutually exclusive with `file`)
	FileURL *string `multipartForm:"name=file_url"`
}

func (c CreateTemplateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTemplateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTemplateRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateTemplateRequest) GetFile() *File {
	if c == nil {
		return nil
	}
	return c.File
}

func (c *CreateTemplateRequest) GetFileURL() *string {
	if c == nil {
		return nil
	}
	return c.FileURL
}

type CreateTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Template created
	TemplateResponse *components.TemplateResponse
}

func (c CreateTemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTemplateResponse) GetTemplateResponse() *components.TemplateResponse {
	if c == nil {
		return nil
	}
	return c.TemplateResponse
}
