// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type CreateRequestRequestBody struct {
	// ID of the template to fill
	TemplateID string `json:"template_id"`
	// Map of field names to values. Text fields accept strings. Checkbox fields accept "checked" or "unchecked".
	Fields map[string]string `json:"fields,omitzero"`
	// Map of signer label to signer configuration. Each key is a signer label defined in the template's signature placements. Omit entirely for fill-only requests.
	//
	Signers map[string]components.SignerInput `json:"signers,omitzero"`
	// Display title for the request. Defaults to the template name. Shown in emails and dashboards.
	Title *string `json:"title,omitzero"`
	// Custom message included in signing emails sent to signers.
	Message *string `json:"message,omitzero"`
	// Arbitrary key-value pairs for your own use (max 10 keys, key max 128 chars, value max 1024 chars)
	Metadata map[string]string `json:"metadata,omitzero"`
	// Whether signers can type their name as a signature instead of drawing or uploading one. Defaults to true.
	//
	AllowTypedSignature *bool `default:"true" json:"allow_typed_signature"`
}

func (c CreateRequestRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRequestRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRequestRequestBody) GetTemplateID() string {
	if c == nil {
		return ""
	}
	return c.TemplateID
}

func (c *CreateRequestRequestBody) GetFields() map[string]string {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateRequestRequestBody) GetSigners() map[string]components.SignerInput {
	if c == nil {
		return nil
	}
	return c.Signers
}

func (c *CreateRequestRequestBody) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *CreateRequestRequestBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateRequestRequestBody) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateRequestRequestBody) GetAllowTypedSignature() *bool {
	if c == nil {
		return nil
	}
	return c.AllowTypedSignature
}

type CreateRequestRequest struct {
	// Optional. If provided, ensures the request is processed at most once within 24 hours. Retries with the same key and body return the original response without creating a duplicate. Using the same key with a different request body returns 409 Conflict.
	//
	IdempotencyKey *string                  `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           CreateRequestRequestBody `request:"mediaType=application/json"`
}

func (c *CreateRequestRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateRequestRequest) GetBody() CreateRequestRequestBody {
	if c == nil {
		return CreateRequestRequestBody{}
	}
	return c.Body
}

type CreateRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Request created
	RequestResponse *components.RequestResponse
}

func (c CreateRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateRequestResponse) GetRequestResponse() *components.RequestResponse {
	if c == nil {
		return nil
	}
	return c.RequestResponse
}
