// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type DeleteWebhookRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteWebhookRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
