// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
	"io"
)

type DownloadSignerSignatureRequest struct {
	// Request ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Signer ID
	Sid string `pathParam:"style=simple,explode=false,name=sid"`
}

func (d *DownloadSignerSignatureRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DownloadSignerSignatureRequest) GetSid() string {
	if d == nil {
		return ""
	}
	return d.Sid
}

type DownloadSignerSignatureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Signature image
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (d *DownloadSignerSignatureResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DownloadSignerSignatureResponse) GetResponseStream() io.ReadCloser {
	if d == nil {
		return nil
	}
	return d.ResponseStream
}
