// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
	"io"
)

type DownloadRequestRequest struct {
	// Request ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DownloadRequestRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DownloadRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// PDF file
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
	Headers        map[string][]string
}

func (d *DownloadRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DownloadRequestResponse) GetResponseStream() io.ReadCloser {
	if d == nil {
		return nil
	}
	return d.ResponseStream
}

func (d *DownloadRequestResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
