// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

// GetAccountResponseBody - Account info
type GetAccountResponseBody struct {
	Account components.Account `json:"account"`
}

func (g *GetAccountResponseBody) GetAccount() components.Account {
	if g == nil {
		return components.Account{}
	}
	return g.Account
}

type GetAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Account info
	Object *GetAccountResponseBody
}

func (g GetAccountResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountResponse) GetObject() *GetAccountResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
