// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type GetRequestRequest struct {
	// Request ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetRequestRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Request detail including inputs and signers
	RequestResponse *components.RequestResponse
}

func (g GetRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRequestResponse) GetRequestResponse() *components.RequestResponse {
	if g == nil {
		return nil
	}
	return g.RequestResponse
}
