// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type GetTemplateRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetTemplateRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Template detail with fields
	TemplateResponse *components.TemplateResponse
}

func (g GetTemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTemplateResponse) GetTemplateResponse() *components.TemplateResponse {
	if g == nil {
		return nil
	}
	return g.TemplateResponse
}
