// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type GetWebhookRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetWebhookRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook details
	WebhookResponse *components.WebhookResponse
}

func (g GetWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWebhookResponse) GetWebhookResponse() *components.WebhookResponse {
	if g == nil {
		return nil
	}
	return g.WebhookResponse
}
