// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
	"time"
)

type ListRequestsRequest struct {
	Page     *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page_size"`
	// Filter by request status
	Status *components.RequestStatus `queryParam:"style=form,explode=true,name=status"`
	// Only return requests created on or after this timestamp (RFC 3339)
	From *time.Time `queryParam:"style=form,explode=true,name=from"`
	// Only return requests created on or before this timestamp (RFC 3339)
	To *time.Time `queryParam:"style=form,explode=true,name=to"`
	// Filter by metadata key. Must be used together with metadata_value.
	MetadataKey *string `queryParam:"style=form,explode=true,name=metadata_key"`
	// Filter by metadata value (exact match). Must be used together with metadata_key.
	MetadataValue *string `queryParam:"style=form,explode=true,name=metadata_value"`
}

func (l ListRequestsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRequestsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListRequestsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListRequestsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListRequestsRequest) GetStatus() *components.RequestStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListRequestsRequest) GetFrom() *time.Time {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListRequestsRequest) GetTo() *time.Time {
	if l == nil {
		return nil
	}
	return l.To
}

func (l *ListRequestsRequest) GetMetadataKey() *string {
	if l == nil {
		return nil
	}
	return l.MetadataKey
}

func (l *ListRequestsRequest) GetMetadataValue() *string {
	if l == nil {
		return nil
	}
	return l.MetadataValue
}

type ListRequestsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of requests
	RequestListResponse *components.RequestListResponse

	Next func() (*ListRequestsResponse, error)
}

func (l ListRequestsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRequestsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListRequestsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListRequestsResponse) GetRequestListResponse() *components.RequestListResponse {
	if l == nil {
		return nil
	}
	return l.RequestListResponse
}
