// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/servants-of-the-server-fire/paraph-go/models/components"
)

type TestWebhookRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (t *TestWebhookRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

type TestWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (t *TestWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}
