// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Plan string

const (
	PlanFree       Plan = "free"
	PlanPro        Plan = "pro"
	PlanEnterprise Plan = "enterprise"
)

func (e Plan) ToPointer() *Plan {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Plan) IsExact() bool {
	if e != nil {
		switch *e {
		case "free", "pro", "enterprise":
			return true
		}
	}
	return false
}

type Limits struct {
	// -1 means unlimited
	RequestsPerMonth int64 `json:"requests_per_month"`
	// -1 means unlimited
	SigningRequestsPerMonth int64 `json:"signing_requests_per_month"`
	// -1 means unlimited
	MaxTemplates int64 `json:"max_templates"`
	// -1 means unlimited
	MaxMembers int64 `json:"max_members"`
}

func (l *Limits) GetRequestsPerMonth() int64 {
	if l == nil {
		return 0
	}
	return l.RequestsPerMonth
}

func (l *Limits) GetSigningRequestsPerMonth() int64 {
	if l == nil {
		return 0
	}
	return l.SigningRequestsPerMonth
}

func (l *Limits) GetMaxTemplates() int64 {
	if l == nil {
		return 0
	}
	return l.MaxTemplates
}

func (l *Limits) GetMaxMembers() int64 {
	if l == nil {
		return 0
	}
	return l.MaxMembers
}

type Usage struct {
	// Requests created in the last 30 days
	Requests int64 `json:"requests"`
	// Signing tasks created in the last 30 days
	SigningRequests int64 `json:"signing_requests"`
	// Total templates in the account
	Templates int64 `json:"templates"`
	// Total team members
	Members int64 `json:"members"`
}

func (u *Usage) GetRequests() int64 {
	if u == nil {
		return 0
	}
	return u.Requests
}

func (u *Usage) GetSigningRequests() int64 {
	if u == nil {
		return 0
	}
	return u.SigningRequests
}

func (u *Usage) GetTemplates() int64 {
	if u == nil {
		return 0
	}
	return u.Templates
}

func (u *Usage) GetMembers() int64 {
	if u == nil {
		return 0
	}
	return u.Members
}

type Account struct {
	TeamName    string `json:"team_name"`
	Plan        Plan   `json:"plan"`
	SandboxMode bool   `json:"sandbox_mode"`
	// Name of the API key used for this request
	APIKeyName string `json:"api_key_name"`
	Limits     Limits `json:"limits"`
	Usage      Usage  `json:"usage"`
}

func (a *Account) GetTeamName() string {
	if a == nil {
		return ""
	}
	return a.TeamName
}

func (a *Account) GetPlan() Plan {
	if a == nil {
		return Plan("")
	}
	return a.Plan
}

func (a *Account) GetSandboxMode() bool {
	if a == nil {
		return false
	}
	return a.SandboxMode
}

func (a *Account) GetAPIKeyName() string {
	if a == nil {
		return ""
	}
	return a.APIKeyName
}

func (a *Account) GetLimits() Limits {
	if a == nil {
		return Limits{}
	}
	return a.Limits
}

func (a *Account) GetUsage() Usage {
	if a == nil {
		return Usage{}
	}
	return a.Usage
}
