// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"time"
)

// DocumentRequestStatus - Request status
type DocumentRequestStatus string

const (
	DocumentRequestStatusSuccess   DocumentRequestStatus = "success"
	DocumentRequestStatusError     DocumentRequestStatus = "error"
	DocumentRequestStatusPending   DocumentRequestStatus = "pending"
	DocumentRequestStatusCancelled DocumentRequestStatus = "cancelled"
)

func (e DocumentRequestStatus) ToPointer() *DocumentRequestStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DocumentRequestStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "success", "error", "pending", "cancelled":
			return true
		}
	}
	return false
}

// DocumentRequest - Full request representation returned by detail and create endpoints. Includes inputs, metadata, and signers.
type DocumentRequest struct {
	ID         string `json:"id"`
	TemplateID string `json:"template_id"`
	// Display title for the request
	Title *string `json:"title,omitzero"`
	// Custom message included in signing emails
	Message *string `json:"message,omitzero"`
	// Request status
	Status DocumentRequestStatus `json:"status"`
	// Whether this request includes signers
	HasSigning bool      `json:"has_signing"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	// Field values used to fill the template
	Inputs map[string]string `json:"inputs,omitzero"`
	// Arbitrary key-value pairs for your own use (max 10 keys, key max 128 chars, value max 1024 chars)
	Metadata map[string]string `json:"metadata,omitzero"`
	// Signers attached to this request, if any
	Signers []Signer `json:"signers,omitzero"`
}

func (d DocumentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DocumentRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DocumentRequest) GetTemplateID() string {
	if d == nil {
		return ""
	}
	return d.TemplateID
}

func (d *DocumentRequest) GetTitle() *string {
	if d == nil {
		return nil
	}
	return d.Title
}

func (d *DocumentRequest) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DocumentRequest) GetStatus() DocumentRequestStatus {
	if d == nil {
		return DocumentRequestStatus("")
	}
	return d.Status
}

func (d *DocumentRequest) GetHasSigning() bool {
	if d == nil {
		return false
	}
	return d.HasSigning
}

func (d *DocumentRequest) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DocumentRequest) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *DocumentRequest) GetInputs() map[string]string {
	if d == nil {
		return nil
	}
	return d.Inputs
}

func (d *DocumentRequest) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DocumentRequest) GetSigners() []Signer {
	if d == nil {
		return nil
	}
	return d.Signers
}
