// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"time"
)

// DocumentRequestSummary - Compact request representation returned in list endpoints. Use GET /requests/{id} for full details including inputs, metadata, and signers.
type DocumentRequestSummary struct {
	ID         string  `json:"id"`
	TemplateID string  `json:"template_id"`
	Title      *string `json:"title,omitzero"`
	// Lifecycle status of a document request.
	// - `success` — fill completed (and all signers signed, if any)
	// - `error` — terminal failure
	// - `pending` — awaiting signer action
	// - `cancelled` — caller cancelled before completion
	//
	Status     RequestStatus `json:"status"`
	HasSigning bool          `json:"has_signing"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

func (d DocumentRequestSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentRequestSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DocumentRequestSummary) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DocumentRequestSummary) GetTemplateID() string {
	if d == nil {
		return ""
	}
	return d.TemplateID
}

func (d *DocumentRequestSummary) GetTitle() *string {
	if d == nil {
		return nil
	}
	return d.Title
}

func (d *DocumentRequestSummary) GetStatus() RequestStatus {
	if d == nil {
		return RequestStatus("")
	}
	return d.Status
}

func (d *DocumentRequestSummary) GetHasSigning() bool {
	if d == nil {
		return false
	}
	return d.HasSigning
}

func (d *DocumentRequestSummary) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DocumentRequestSummary) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}
