// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ErrorName string

const (
	ErrorNameUnauthorized  ErrorName = "unauthorized"
	ErrorNameNotFound      ErrorName = "not_found"
	ErrorNameBadRequest    ErrorName = "bad_request"
	ErrorNameExceededQuota ErrorName = "exceeded_quota"
	ErrorNameExceededRate  ErrorName = "exceeded_rate"
	ErrorNameUnknown       ErrorName = "unknown"
	ErrorNameMergeFailed   ErrorName = "merge_failed"
	ErrorNameInvalidStatus ErrorName = "invalid_status"
)

func (e ErrorName) ToPointer() *ErrorName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ErrorName) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized", "not_found", "bad_request", "exceeded_quota", "exceeded_rate", "unknown", "merge_failed", "invalid_status":
			return true
		}
	}
	return false
}

type Error struct {
	ErrorName ErrorName `json:"error_name"`
	ErrorMsg  string    `json:"error_msg"`
}

func (e *Error) GetErrorName() ErrorName {
	if e == nil {
		return ErrorName("")
	}
	return e.ErrorName
}

func (e *Error) GetErrorMsg() string {
	if e == nil {
		return ""
	}
	return e.ErrorMsg
}
