// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Type - AcroForm field type
type Type string

const (
	TypeText       Type = "text"
	TypeDate       Type = "date"
	TypeCheckbox   Type = "checkbox"
	TypeCombobox   Type = "combobox"
	TypeListbox    Type = "listbox"
	TypeRadioGroup Type = "radio_group"
)

func (e Type) ToPointer() *Type {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Type) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "date", "checkbox", "combobox", "listbox", "radio_group":
			return true
		}
	}
	return false
}

type Field struct {
	ID string `json:"id"`
	// Field name as defined in the PDF form
	Name string `json:"name"`
	// AcroForm field type
	Type Type `json:"type"`
	// Available options for ComboBox, ListBox, or RadioButtonGroup fields
	Options []string `json:"options"`
}

func (f *Field) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *Field) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *Field) GetType() Type {
	if f == nil {
		return Type("")
	}
	return f.Type
}

func (f *Field) GetOptions() []string {
	if f == nil {
		return []string{}
	}
	return f.Options
}
