// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
)

type RequestListResponse struct {
	Requests []DocumentRequestSummary `json:"requests,omitzero"`
	ListInfo *ListInfo                `json:"list_info,omitzero"`
}

func (r RequestListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RequestListResponse) GetRequests() []DocumentRequestSummary {
	if r == nil {
		return nil
	}
	return r.Requests
}

func (r *RequestListResponse) GetListInfo() *ListInfo {
	if r == nil {
		return nil
	}
	return r.ListInfo
}
