// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
)

type RequestResponse struct {
	// Full request representation returned by detail and create endpoints. Includes inputs, metadata, and signers.
	Request *DocumentRequest `json:"request,omitzero"`
}

func (r RequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RequestResponse) GetRequest() *DocumentRequest {
	if r == nil {
		return nil
	}
	return r.Request
}
