// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SignerStatus - Per-signer status.
// - `pending` — signing link sent, awaiting signer
// - `signed` — signer completed
// - `expired` — signer did not sign before `expires_at`
// - `error` — terminal failure for this signer
// - `cancelled` — parent request was cancelled
type SignerStatus string

const (
	SignerStatusPending   SignerStatus = "pending"
	SignerStatusSigned    SignerStatus = "signed"
	SignerStatusExpired   SignerStatus = "expired"
	SignerStatusError     SignerStatus = "error"
	SignerStatusCancelled SignerStatus = "cancelled"
)

func (e SignerStatus) ToPointer() *SignerStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SignerStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "signed", "expired", "error", "cancelled":
			return true
		}
	}
	return false
}
