// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignaturePlacement struct {
	ID string `json:"id"`
	// Label identifying which signer this placement belongs to
	SignerLabel string `json:"signer_label"`
	PageNumber  int64  `json:"page_number"`
	// X coordinate in PDF points from the left edge of the page
	X float64 `json:"x"`
	// Y coordinate in PDF points from the bottom edge of the page
	Y      float64 `json:"y"`
	Width  float64 `json:"width"`
	Height float64 `json:"height"`
}

func (s *SignaturePlacement) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SignaturePlacement) GetSignerLabel() string {
	if s == nil {
		return ""
	}
	return s.SignerLabel
}

func (s *SignaturePlacement) GetPageNumber() int64 {
	if s == nil {
		return 0
	}
	return s.PageNumber
}

func (s *SignaturePlacement) GetX() float64 {
	if s == nil {
		return 0.0
	}
	return s.X
}

func (s *SignaturePlacement) GetY() float64 {
	if s == nil {
		return 0.0
	}
	return s.Y
}

func (s *SignaturePlacement) GetWidth() float64 {
	if s == nil {
		return 0.0
	}
	return s.Width
}

func (s *SignaturePlacement) GetHeight() float64 {
	if s == nil {
		return 0.0
	}
	return s.Height
}
