// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"time"
)

type SignerStatus string

const (
	SignerStatusPending   SignerStatus = "pending"
	SignerStatusSigned    SignerStatus = "signed"
	SignerStatusExpired   SignerStatus = "expired"
	SignerStatusError     SignerStatus = "error"
	SignerStatusCancelled SignerStatus = "cancelled"
)

func (e SignerStatus) ToPointer() *SignerStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SignerStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "signed", "expired", "error", "cancelled":
			return true
		}
	}
	return false
}

type Signer struct {
	ID string `json:"id"`
	// Role label for this signer (e.g. "Employee", "Manager")
	SignerLabel    string       `json:"signer_label"`
	RecipientEmail string       `json:"recipient_email"`
	Status         SignerStatus `json:"status"`
	// When the signing link expires
	ExpiresAt *time.Time `json:"expires_at,omitzero"`
	// When the signer completed signing
	SignedAt *time.Time `json:"signed_at,omitzero"`
}

func (s Signer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Signer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Signer) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Signer) GetSignerLabel() string {
	if s == nil {
		return ""
	}
	return s.SignerLabel
}

func (s *Signer) GetRecipientEmail() string {
	if s == nil {
		return ""
	}
	return s.RecipientEmail
}

func (s *Signer) GetStatus() SignerStatus {
	if s == nil {
		return SignerStatus("")
	}
	return s.Status
}

func (s *Signer) GetExpiresAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ExpiresAt
}

func (s *Signer) GetSignedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.SignedAt
}
