// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"time"
)

type TemplateDetail struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Arbitrary key-value pairs (max 10 keys, key max 128 chars, value max 1024 chars)
	Metadata  map[string]string `json:"metadata,omitzero"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
	// Form fields detected in the uploaded PDF
	Fields []Field `json:"fields"`
	// Signature placement regions configured on this template
	SignaturePlacements []SignaturePlacement `json:"signature_placements"`
}

func (t TemplateDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplateDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplateDetail) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TemplateDetail) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TemplateDetail) GetMetadata() map[string]string {
	if t == nil {
		return nil
	}
	return t.Metadata
}

func (t *TemplateDetail) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TemplateDetail) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}

func (t *TemplateDetail) GetFields() []Field {
	if t == nil {
		return []Field{}
	}
	return t.Fields
}

func (t *TemplateDetail) GetSignaturePlacements() []SignaturePlacement {
	if t == nil {
		return []SignaturePlacement{}
	}
	return t.SignaturePlacements
}
