// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"time"
)

type Template struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Arbitrary key-value pairs (max 10 keys, key max 128 chars, value max 1024 chars)
	Metadata  map[string]string `json:"metadata,omitzero"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
}

func (t Template) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Template) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Template) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Template) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Template) GetMetadata() map[string]string {
	if t == nil {
		return nil
	}
	return t.Metadata
}

func (t *Template) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *Template) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
