// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
)

type TemplateResponse struct {
	Template *TemplateDetail `json:"template,omitzero"`
}

func (t TemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplateResponse) GetTemplate() *TemplateDetail {
	if t == nil {
		return nil
	}
	return t.Template
}
