// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
)

type WebhookResponse struct {
	Webhook *Webhook `json:"webhook,omitzero"`
}

func (w WebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookResponse) GetWebhook() *Webhook {
	if w == nil {
		return nil
	}
	return w.Webhook
}
