// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WebhookEvent - Event types. `request.created`, `request.success`, `request.cancelled`, `request.error`, and `signer.signed` are dispatched for their respective lifecycle events. `webhook.test` is sent when you use the test endpoint to verify your webhook URL.
type WebhookEvent string

const (
	WebhookEventRequestCreated   WebhookEvent = "request.created"
	WebhookEventRequestSuccess   WebhookEvent = "request.success"
	WebhookEventRequestCancelled WebhookEvent = "request.cancelled"
	WebhookEventRequestError     WebhookEvent = "request.error"
	WebhookEventSignerSigned     WebhookEvent = "signer.signed"
	WebhookEventWebhookTest      WebhookEvent = "webhook.test"
)

func (e WebhookEvent) ToPointer() *WebhookEvent {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WebhookEvent) IsExact() bool {
	if e != nil {
		switch *e {
		case "request.created", "request.success", "request.cancelled", "request.error", "signer.signed", "webhook.test":
			return true
		}
	}
	return false
}
