// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
)

type WebhookListResponse struct {
	Webhooks []Webhook `json:"webhooks,omitzero"`
	ListInfo *ListInfo `json:"list_info,omitzero"`
}

func (w WebhookListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookListResponse) GetWebhooks() []Webhook {
	if w == nil {
		return nil
	}
	return w.Webhooks
}

func (w *WebhookListResponse) GetListInfo() *ListInfo {
	if w == nil {
		return nil
	}
	return w.ListInfo
}
