// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/servants-of-the-server-fire/paraph-go/internal/utils"
	"time"
)

type Webhook struct {
	ID        string         `json:"id"`
	URL       string         `json:"url"`
	Events    []WebhookEvent `json:"events"`
	Active    bool           `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (w Webhook) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *Webhook) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *Webhook) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *Webhook) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *Webhook) GetEvents() []WebhookEvent {
	if w == nil {
		return []WebhookEvent{}
	}
	return w.Events
}

func (w *Webhook) GetActive() bool {
	if w == nil {
		return false
	}
	return w.Active
}

func (w *Webhook) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *Webhook) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}
