workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Paraph API:
        inputs:
            - location: ../paraph/openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/paraph/paraph/paraph-api
targets:
    paraph:
        target: go
        source: Paraph API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/paraph/paraph/paraph-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
